Identity_Sample/Areas/Admin/Pages/Role/Add.cshtml.cs
using System.ComponentModel.DataAnnotations;
using Identity_Sample.Data;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Identity_Sample.Areas.Admin.Pages.Role
{
    public class AddModel : PageModel
    {
        private readonly RoleManager<IdentityRole> _roleManager;
        private readonly AppDBContext _appDBContext;
        public AddModel(RoleManager<IdentityRole> roleManager, AppDBContext appDBContext)
        {
            _roleManager = roleManager;
            _appDBContext = appDBContext;
        }
        [TempData]
        public string StatusMessage { get; set; }
        public class InputModel
        {
            public string ID { get; set; }
            [Required(ErrorMessage = "Please enter role name")]
            [Display(Name = "Role Name")]
            [StringLength(100, ErrorMessage = "{0} must be {2} and {1} characters long.", MinimumLength = 3)]
            public string Name { get; set; }
        }
        [BindProperty]
        public InputModel Input { get; set; }
        [BindProperty]
        public bool IsUpdate { get; set; }

        public IActionResult OnGet() => NotFound("Not Found");
        public IActionResult OnPost() => NotFound("Not Found");

        public IActionResult OnPostStartNewRole()
        {
            StatusMessage = "Please enter new role information";
            IsUpdate = false;
            ModelState.Clear();
            return Page();
        }

        public async Task<IActionResult> OnPostStartUpdate()
        {
            StatusMessage = null;
            IsUpdate = true;
            if (Input.ID == null)
            {
                StatusMessage = "Error: No information about role";
                return Page();
            }
            var result = await _roleManager.FindByIdAsync(Input.ID);
            if (result != null)
            {
                Input.Name = result.Name;
                ViewData["Title"] = "Update role " + Input.Name;
                ModelState.Clear();
            }
            else
            {
                StatusMessage = "Error: No information about role ID " + Input.ID;
            }
            return Page();
        }
        public async Task<IActionResult> OnPostAddOrUpdate()
        {

            if (!ModelState.IsValid)
            {
                StatusMessage = null;
                return Page();
            }
            if (IsUpdate)
            {
                if (Input.ID == null)
                {
                    ModelState.Clear();
                    StatusMessage = "Error: No information about role";
                    return Page();
                }
                var result = await _roleManager.FindByIdAsync(Input.ID);
                if (result != null)
                {
                    result.Name = Input.Name;
                    var roleUpdateRs = await _roleManager.UpdateAsync(result);
                    if (roleUpdateRs.Succeeded)
                    {
                        StatusMessage = "Update role successfully.";
                    }
                    else
                    {
                        StatusMessage = "Error: ";
                        foreach (var er in roleUpdateRs.Errors)
                        {
                            StatusMessage += er.Description;
                        }
                    }
                }
                else
                {
                    StatusMessage = "Error: Cannot find role to update.";
                }
            }
            else
            {
                var newRole = new IdentityRole(Input.Name);
                newRole.Id = Guid.NewGuid().ToString();
                var rsNewRole = await _roleManager.CreateAsync(newRole);
                if (rsNewRole.Succeeded)
                {
                    StatusMessage = $"Created role {newRole.Name} successfully.";
                    return RedirectToPage("./Index");
                }
                else
                {
                    StatusMessage = "Error: ";
                    foreach (var er in rsNewRole.Errors)
                    {
                        StatusMessage += er.Description;
                    }
                }
            }
            return Page();
        }
    }
}

Identity_Sample/Areas/Admin/Pages/Role/AddUserRole.cshtml.cs
using System.ComponentModel.DataAnnotations;
using Identity_Sample.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;

namespace Identity_Sample.Areas.Admin.Pages.Role
{
    public class AddUserRole : PageModel
    {
        private readonly RoleManager<IdentityRole> _roleManager;
        private readonly UserManager<AppUser> _userManager;

        public AddUserRole(RoleManager<IdentityRole> roleManager, UserManager<AppUser> userManager)
        {
            _roleManager = roleManager;
            _userManager = userManager;
        }

        public class InputModel
        {
            [Required] public string ID { get; set; }
            public string? Name { get; set; }
            public string[] RoleNames { get; set; }
        }

        [BindProperty] public InputModel Input { get; set; }
        [BindProperty] public bool isConfirmed { get; set; }
        [TempData] public string StatusMessage { get; set; }

        public IActionResult OnGet() => NotFound("Not Found");

        public List<string> AllRoles { get; set; } = new List<string>();

        public async Task<IActionResult> OnPost()
        {
            var user = await _userManager.FindByIdAsync(Input.ID);
            if (user == null)
            {
                return NotFound("Cannot find role to delete.");
            }

            var roles = await _userManager.GetRolesAsync(user);
            var allRoles = await _roleManager.Roles.ToListAsync();
            allRoles.ForEach(r => { AllRoles.Add(r.Name); });
            if (!isConfirmed)
            {
                Input.RoleNames = roles.ToArray();
                isConfirmed = true;
                StatusMessage = "";
                ModelState.Clear();
            }
            else
            {
                StatusMessage = "Updated";
                if (Input.RoleNames == null)
                {
                    Input.RoleNames = new string[] { };
                }
                foreach (var roleName in Input.RoleNames)
                {
                    if (roles.Contains(roleName)) continue;
                    await _userManager.AddToRoleAsync(user, roleName);
                }
                foreach (var roleName in roles)
                {
                    if (Input.RoleNames.Contains(roleName)) continue;
                    await _userManager.RemoveFromRoleAsync(user, roleName);
                }
            }

            Input.Name = user.UserName;
            return Page();
        }
    }
}

Identity_Sample/Areas/Admin/Pages/Role/Delete.cshtml.cs
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Identity_Sample.Areas.Admin.Pages.Role
{
    public class DeleteModel : PageModel
    {
        private readonly RoleManager<IdentityRole> _roleManager;
        public DeleteModel(RoleManager<IdentityRole> roleManager)
        {
            _roleManager = roleManager;
        }
        public class InputModel
        {
            [Required]
            public string? ID { get; set; }
            public string? Name { get; set; }
        }
        [BindProperty]
        public InputModel Input { get; set; }
        [BindProperty]
        public bool isConfirmed { get; set; }
        [TempData]
        public string StatusMessage { get; set; }

        public IActionResult OnGet() => NotFound("Not Found");
        public async Task<IActionResult> OnPost()
        {
            if (!ModelState.IsValid)
            {
                return NotFound("Cannot delete role.");
            }
            var role = await _roleManager.FindByIdAsync(Input.ID);
            if (role == null)
            {
                return NotFound("Cannot find role to delete.");
            }
            ModelState.Clear();
            if (isConfirmed)
            {
                await _roleManager.DeleteAsync(role);
                StatusMessage = "Deleted " + role.Name;
                return RedirectToPage("Index");
            }
            else
            {
                Input.Name = role.Name;
                isConfirmed = true;
            }
            return Page();
        }
    }
}

Identity_Sample/Areas/Admin/Pages/Role/Index.cshtml.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;

namespace Identity_Sample.Areas.Admin.Pages.Role
{
    public class IndexModel : PageModel
    {
        private readonly RoleManager<IdentityRole> _roleManager;
        public IndexModel(RoleManager<IdentityRole> roleManager)
        {
            _roleManager = roleManager;
        }
        public List<IdentityRole> roles { get; set; }
        [TempData]
        public string StatusMessage { get; set; }
        public async Task<IActionResult> OnGet()
        {
            roles = await _roleManager.Roles.ToListAsync();
            return Page();
        }
    }
}

Identity_Sample/Areas/Admin/Pages/Role/User.cshtml.cs
using Identity_Sample.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;

namespace Identity_Sample.Areas.Admin.Pages.Role
{
    public class UserModel : PageModel
    {
        const int USERS_PER_PAGE = 10;
        private readonly RoleManager<IdentityRole> _roleManager;
        private readonly UserManager<AppUser> _userManager;
        public UserModel(RoleManager<IdentityRole> roleManager, UserManager<AppUser> userManager)
        {
            _roleManager = roleManager;
            _userManager = userManager;
        }
        public class UserInList : AppUser
        {
            public string listRoles { get; set; }
        }

        public List<UserInList> users;
        public int totalPages { get; set; }
        [TempData]
        public string StatusMessage { get; set; }
        [BindProperty(SupportsGet = true)]
        public int pageNumber { get; set; }

        public IActionResult OnPost() => NotFound("Not allowed");
        public async Task<IActionResult> OnGet()
        {
            var cuser = await _userManager.GetUserAsync(User);
            // await _userManager.AddToRolesAsync(cuser, new string[] { "Role02" });
            if (pageNumber == 0)
            {
                pageNumber = 1;
            }
            var lusers = (from u in _userManager.Users
                          orderby u.UserName
                          select new UserInList()
                          {
                              Id = u.Id,
                              UserName = u.UserName
                          });
            int totalUsers = await lusers.CountAsync();
            totalPages = (int)Math.Ceiling((double)totalUsers / USERS_PER_PAGE);
            users = await lusers.Skip(USERS_PER_PAGE * (pageNumber - 1)).Take(USERS_PER_PAGE).ToListAsync();
            foreach (var user in users)
            {
                var roles = await _userManager.GetRolesAsync(user);
                user.listRoles = string.Join(",", roles.ToList());
            }
            return Page();
        }
    }
}

Identity_Sample/Areas/Admin/Pages/RoleClaims/Delete.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Identity_Sample.Areas.Admin.Pages.RoleClaims;
using Identity_Sample.Data;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;

namespace Identity_Sample.Areas.Admin.Pages.RoleClaims
{
    public class DeleteModel : PageModel
    {
        private readonly AppDBContext _context;
        private readonly RoleManager<IdentityRole> _roleManager;

        public IdentityRole role { set; get; }

        [BindProperty(SupportsGet = true)]
        public string roleid { set; get; }

        public DeleteModel(AppDBContext context, RoleManager<IdentityRole> roleManager)
        {
            _context = context;
            _roleManager = roleManager;
        }

        async Task<IdentityRole> GetRole()
        {

            if (string.IsNullOrEmpty(roleid)) return null;
            return await _roleManager.FindByIdAsync(roleid);
        }

        [BindProperty]
        public IdentityRoleClaim<string> EditClaim { get; set; }

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            role = await GetRole();
            if (role == null)
                return NotFound("Not found role");

            if (id == null)
            {
                return NotFound();
            }

            EditClaim = await _context.RoleClaims.FirstOrDefaultAsync(m => m.Id == id);

            if (EditClaim == null)
            {
                return NotFound();
            }
            return Page();
        }

        public async Task<IActionResult> OnPostAsync(int? id)
        {

            role = await GetRole();
            if (role == null)
                return NotFound("Not found Role");

            if (id == null)
            {
                return NotFound();
            }

            EditClaim = await _context.RoleClaims.FindAsync(id);

            if (EditClaim != null)
            {
                _context.RoleClaims.Remove(EditClaim);
                await _context.SaveChangesAsync();
            }

            return RedirectToPage("./Index", new { roleid = roleid });
        }
    }
}

Identity_Sample/Areas/Admin/Pages/Role/Add.cshtml
@page
@model Identity_Sample.Areas.Admin.Pages.Role.AddModel
@{
    var btnText = Model.IsUpdate ? "Update" : "Create";
}

<h4>@ViewData["Title"]</h4>
<partial name="_StatusMessage" model="@Model.StatusMessage"/>
<div class="row">
    <div class="col-md-6">
        <form method="POST">
            <div asp-validation-summary="All" class="text-danger"></div>
            <input type="hidden" asp-for="Input.ID" value="Abcs">
            <input type="hidden" asp-for="IsUpdate">
            <div class="form-group">
                <label asp-for="Input.Name"></label>
                <input asp-for="Input.Name" class="form-control">
                <span asp-validation-for="Input.Name" class="text-danger"></span>
            </div>

            <button id="add-or-edit-role" type="submit"
                    asp-page-handler="AddOrUpdate" class="btn btn-primary">@btnText</button>

            <a class="btn btn-primary" asp-page="./Index">Role List</a>
        </form>
    </div>
</div>

@section Scripts{
    <partial name="_ValidationScriptsPartial"/>
}

Identity_Sample/Areas/Admin/Pages/Role/AddUserRole.cshtml
@page
@model Identity_Sample.Areas.Admin.Pages.Role.AddUserRole
@{
    ViewData["Title"] = "Update Role for User";
}

<h4>@ViewData["Title"]</h4>
<div class="row">
    <div class="col-md-6">
        <p>Choose role to assign to <strong>@Model.Input.Name</strong></p>
        <form method="POST">
            <partial name="_StatusMessage" model="@Model.StatusMessage"/>
            <div class="form-group">
                @Html.LabelFor(x => x.Input.RoleNames)
                @Html.ListBoxFor(x => x.Input.RoleNames,
                    new SelectList(Model.AllRoles),
                    new { @class = "w-100", id = "selectrole" })
            </div>
            <div asp-validation-summary="All" class="text-danger"></div>
            <input type="hidden" asp-for="Input.ID"></input>
            <input type="hidden" asp-for="isConfirmed"></input>
            <a class="btn btn-primary" asp-page="./User">User List</a>
            <button type="submit" class="btn btn-danger">Update</button>
        </form>
    </div>
</div>

@section Scripts
{
    <script src="https://unpkg.com/multiple-select@1.5.2/dist/multiple-select.min.js"></script>
    <link rel="stylesheet" href="https://unpkg.com/multiple-select@1.5.2/dist/multiple-select.min.css"/>
    <script>
        $('selectrole').multipleSelect({
            selectAll: false,
            keepOpen: false,
            isOpen: false
        });
    </script>
    <partial name="_ValidationScriptsPartial"/>
}

Identity_Sample/Areas/Admin/Pages/Role/Delete.cshtml
@page
@model Identity_Sample.Areas.Admin.Pages.Role.DeleteModel
@{
    ViewData["Title"] = "Delete role";
}

<h4>@ViewData["Title"]</h4>
<div class="row">
    <div class="col-md-6">
        <p>Are you sure you want to delete role <strong>@Model.Input.Name</strong>?</p>
        <form method="POST">
            <div asp-validation-summary="All" class="text-danger"></div>
            <input type="hidden" asp-for="Input.ID">
            <input type="hidden" asp-for="isConfirmed">
            <a class="btn btn-primary" asp-page="./Index">Role List</a>
            <button type="submit" asp-page="./Delete" class="btn btn-danger">Delete</button>
        </form>
    </div>
</div>

@section Scripts{
    <partial name="_ValidationScriptsPartial"/>
}

Identity_Sample/Areas/Admin/Pages/Role/Index.cshtml
@page
@model IndexModel

<h3>Role List</h3>
<partial name="_StatusMessage" model="@Model.StatusMessage"/>

<form method="POST" class="my-1 d-inline">
    <button class="btn btn-secondary" asp-page="./Add"
            asp-page-handler="StartNewRole">
        Add new Role
    </button>
</form>
<a class="btn btn-secondary" asp-page="./User">Set Role to Account</a>
<table class="table">
    <tr>
        <th>Role ID</th>
        <th>Name</th>
        <th>Action</th>
    </tr>
    @foreach (var role in @Model.roles)
    {
        <tr>
            <td>@role.Id</td>
            <td>@role.Name</td>
            <td>
                <form method="POST" class="d-inline">
                    <button name="Input.ID" value="@role.Id" class="btn btn-success btn-sm"
                            asp-page="./Add" asp-page-handler="StartUpdate">
                        Update Role
                    </button>
                </form>
                <a name="rolename" class="btn btn-success btn-sm"
                   asp-route-roleid="@role.Id"
                   asp-area="Admin"
                   asp-page="/RoleClaims/Index">
                    Claims
                </a>
                <form method="POST" class="d-inline">
                    <button name="Input.ID" value="@role.Id" class="btn btn-success btn-sm"
                            asp-page="./Delete">
                        Delete Role
                    </button>
                </form>
            </td>
        </tr>
    }
</table>

Identity_Sample/Areas/Admin/Pages/Role/User.cshtml
@page
@model Identity_Sample.Areas.Admin.Pages.Role.UserModel
@{
    ViewData["Title"] = "USER LISTS";
}

<h4>@ViewData["Title"]</h4>
<partial name="_StatusMessage" model="@Model.StatusMessage"/>
<table class="table table-striped">
    <tr>
        <th>Username</th>
        <th>Roles</th>
        <th>Actions</th>
    </tr>
    @foreach (var user in @Model.users)
    {
        <tr>
            <td>@user.UserName</td>
            <td>@user.listRoles</td>
            <td>
                <form method="POST" class="d-inline">
                    <button name="Input.ID" value="@user.Id" class="btn btn-primary btn-sm"
                            asp-page="./AddUserRole">
                        Update User Role
                    </button>
                </form>
            </td>
        </tr>
    }
</table>

@section Scripts{
    <partial name="_ValidationScriptsPartial"/>
}

@{
    Func<int?, string> generateUrl = (int? _pageNumber) => { return Url.Page("./User", new { pageNumber = _pageNumber }); };

    var dataPaging = new
    {
        currentPage = Model.pageNumber,
        countPages = Model.totalPages,
        generateUrl = generateUrl
    };
}
<partial name="_Paging" model="@dataPaging"/>

Identity_Sample/Areas/Admin/Pages/Role/_StatusMessage.cshtml
@model string

@if (!String.IsNullOrEmpty(Model))
{
    var statusMessageClass = Model.StartsWith("Error") ? "danger" : "success";
    <div class="alert alert-@statusMessageClass alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" 
                 aria-label="Close"><span aria-hidden="true">&times;</span></button>
        @Model
    </div>
}